namespace java thrift.gen.javacode
namespace php ThriftService
typedef i16 short
typedef i32 int
typedef i64 long
typedef string String
typedef binary ThriftByteBuffer
typedef bool boolean

exception ThriftServiceException { 1 : int ecode, 2 : String emsg }

struct ThriftFileBean{
1: String fileKey
2: String fileName
3: String extension
4: ThriftByteBuffer file
5: String filePath
 } 

struct ThriftBoardBean{
1: int id
2: int uid
3: String title
4: String content
5: String date
6: String userName
7: ThriftFileBean file
 } 

struct ThriftUserBean{
1: String userId
2: String userNick
3: String userPwd
4: String userGender
5: int userTall
6: String userProfileImageurl
7: String userIntroduce
8: String deviceID
9: int storeTypeID
10: String registrationKey
11: String appVersion
12: int deviceType
13: String regDate
14: String locate
15: String isFollow
16: int coordiCount
17: int followCount
18: int followerCount
19: String followId
20: String isLeave
21: int isNextPage
22: int totalCount
23: String timeLineNew
24: ThriftListBean listBean
25: int bookMarkCount
26: list<ThriftBoardBean> boardList
 } 

struct ThriftUserResult{
1: int id
2: String userId
3: String userPw
4: String name
5: String date
 } 

struct ThriftListBean{
1: String gid
2: int page
3: int pageBlock
4: int rowPerPage
5: int pagePerBlock
6: long totalRow
7: long virtualNum
8: int totalPage
9: int totalBlock
10: int startPage
11: int endPage
12: int isPrevBlock
13: int isNextBlock
 } 

service ThriftService {  
String duplicateUserId(1:String id) throws (1:ThriftServiceException se)  ; 
list<ThriftFileBean> imgFileUpload(1:list<ThriftFileBean> fileBeans) throws (1:ThriftServiceException se)  ; 
ThriftUserResult getUserInfo(1:String id) throws (1:ThriftServiceException se)  ; 
list<ThriftFileBean> fileUpload(1:list<ThriftFileBean> fileBeans) throws (1:ThriftServiceException se)  ; 
 } 
service ThriftAdminService {  
ThriftUserResult loginUser(1:String userID,2:String userPWD) throws (1:ThriftServiceException se)  ; 
list<ThriftFileBean> imgFileUpload(1:list<ThriftFileBean> fileBeans) throws (1:ThriftServiceException se)  ; 
void updateUser(1:String userId,2:String userPw,3:String name) throws (1:ThriftServiceException se)  ; 
list<ThriftFileBean> fileUpload(1:list<ThriftFileBean> fileBeans) throws (1:ThriftServiceException se)  ; 
void signupUser(1:String userId,2:String userPw,3:String name) throws (1:ThriftServiceException se)  ; 
list<ThriftBoardBean> getBoardAll() throws (1:ThriftServiceException se)  ; 
void writeBoard(1:int uid,2:String title,3:String content,4:list<ThriftFileBean> fileBeans) throws (1:ThriftServiceException se)  ; 
ThriftBoardBean getBoardDetail(1:int id) throws (1:ThriftServiceException se)  ; 
 } 

