namespace java thrift.gen.javacode
namespace php ThriftService
typedef i16 short
typedef i32 int
typedef i64 long
typedef string String
typedef binary ThriftByteBuffer
typedef bool boolean

exception ThriftServiceException { 1 : int ecode, 2 : String emsg }

struct ThriftUserBean{
1: int id
2: String userId
3: String userPw
4: String name
5: String date
 } 

struct ThriftUserResult{
1: int id
2: String userId
3: String userPw
4: String name
5: String date
} 

struct ThriftFileBean{
1: String fileKey
2: String fileName
3: String extension
4: ThriftByteBuffer file
5: String filePath
 } 

struct ThriftListBean{
1: int id
2: int uid
3: String title
4: String content
5: String date
 } 

struct ThriftBoardBean{
1: int id
2: int uid
3: String title
4: String content
5: String date
 } 

service ThriftService {  
String duplicateUserId(1:String id) throws (1:ThriftServiceException se)  ; 
list<ThriftFileBean> imgFileUpload(1:list<ThriftFileBean> fileBeans) throws (1:ThriftServiceException se)  ; 
ThriftUserResult getUserInfo(1:String id) throws (1:ThriftServiceException se)  ; 
list<ThriftFileBean> fileUpload(1:list<ThriftFileBean> fileBeans) throws (1:ThriftServiceException se)  ; 
 }

service ThriftAdminService {
ThriftUserResult loginUser(1:String userID,2:String userPWD) throws (1:ThriftServiceException se)  ; 
list<ThriftFileBean> imgFileUpload(1:list<ThriftFileBean> fileBeans) throws (1:ThriftServiceException se)  ; 
list<ThriftFileBean> fileUpload(1:list<ThriftFileBean> fileBeans) throws (1:ThriftServiceException se)  ; 
 } 

