namespace java thrift.gen.javacode
namespace php ThriftService

typedef i16 short
typedef i32 int
typedef i64 long
typedef string String
typedef binary ThriftByteBuffer
typedef bool boolean

exception ThriftServiceException { 1 : int ecode, 2 : String emsg }

struct ThriftUserBean{
	1. int id
	2: String userId
	3: String userPw
	4: String NAME
	5: String DATE
} 

struct ThriftBoardBean{
	1: int id
	2: int uid
	3: String title
	4: String content
	5: String DATE
}

struct ThriftFileBean{
	1: int id
	2: int bid
	2: String name
	3: String ext
	4: ThriftByteBuffer file
	5: String filePath
	6: String DATE
}

service ThriftService {  
	String duplicateUserId(1:String id) throws (1:ThriftServiceException se);
	list<ThriftFileBean> imgFileUpload(1:list<ThriftFileBean> fileBeans) throws (1:ThriftServiceException se); 
	ThriftUserBean getUserInfo(1:String id) throws (1:ThriftServiceException se);
	list<ThriftFileBean> fileUpload(1:list<ThriftFileBean> fileBeans) throws (1:ThriftServiceException se); 
	ThriftUserBean getTest(1:int userNumber) throws (1:ThriftServiceException se);
}

service ThriftAdminService {  
	list<ThriftFileBean> imgFileUpload(1:list<ThriftFileBean> fileBeans) throws (1:ThriftServiceException se)  ; 
	list<ThriftFileBean> fileUpload(1:list<ThriftFileBean> fileBeans) throws (1:ThriftServiceException se)  ; 
	ThriftUserBean getTest(1:int userNumber) throws (1:ThriftServiceException se)  ; 
} 
